# Generated by Django 2.2.14 on 2022-06-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
