# Generated by Django 2.2.14 on 2022-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/news/'),
        ),
    ]
