# Generated by Django 2.2.14 on 2022-06-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220629_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/images/'),
        ),
    ]
