# Generated by Django 2.2.14 on 2022-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=200)),
                ('Detail', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='images',
        ),
        migrations.AlterField(
            model_name='new',
            name='Detail',
            field=models.TextField(),
        ),
    ]
