# Generated by Django 2.2.14 on 2022-06-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='blogs/images/'),
        ),
    ]
